language: python

python:
  - "3.6"
  - "3.7"

services:
  - docker

jobs:
  include:
    - stage: test
      install: pip install pipenv && pipenv install --dev
      script: pipenv run ./crawler.py --region amsterdam

    - stage: build-docker
      if: type IN (api, cron, push)
      install: docker build --file dev/docker/Dockerfile --tag nstapelbroek/estate-crawler:$TRAVIS_BRANCH --pull .
      script: docker run --rm -it --name my-crawler-instance -v $(pwd):/app/build docker.io/nstapelbroek/estate-crawler --region amsterdam
      after_success:  docker login -u="nstapelbroekbot" -p="$DOCKERHUB_PASSWORD" && docker tag nstapelbroek/estate-crawler:$TRAVIS_BRANCH docker.io/nstapelbroek/estate-crawler:$TRAVIS_BRANCH && docker push docker.io/nstapelbroek/estate-crawler