sudo: false

language: python

install: pip install pipenv --upgrade && pipenv install --dev --skip-lock

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - pipenv run ./crawler.py --region Utrecht
      python: '3.6'
    - stage: test
      script:
        - pipenv run ./crawler.py --region Utrecht
      python: '3.7'
      dist: xenial
      sudo: true

    - stage: build-docker
      if: branch = latest
      install: make validate
      script: docker run --rm -it --name my-crawler-instance -v $(pwd):/app/build nstapelbroek/estate-crawler --region amsterdam
      after_success:  docker login -u="nstapelbroekbot" -p="$DOCKERHUB_PASSWORD" && docker tag nstapelbroek/estate-crawler:$TRAVIS_BRANCH docker.io/nstapelbroek/estate-crawler:$TRAVIS_BRANCH && docker push docker.io/nstapelbroek/estate-crawler