language: python

python:
  - "2.7"

jobs:
  include:
    - stage: test
      install: pip install -r requirements.txt
      script: ./crawler.py --region amsterdam

    - stage: build-docker
      if: type IN (api, cron, push)
      install: docker build --tag nstapelbroek/estate-crawler:$TRAVIS_BRANCH --pull .
      script: docker run --rm -it --name my-crawler-instance -v $(pwd):/app/build docker.io/nstapelbroek/estate-crawler --region amsterdam
      after_success:  docker login -u="nstapelbroekbot" -p="$DOCKERHUB_PASSWORD" && \
                      docker tag nstapelbroek/estate-crawler:$TRAVIS_BRANCH docker.io/nstapelbroek/estate-crawler:$TRAVIS_BRANCH && \
                      docker push docker.io/nstapelbroek/estate-crawler